### PR TITLE
NSInvalidArgumentException fixed

### PR DESCRIPTION
**Pull request by antonargunov**
- NSInvalidArgumentException fixed
- Security.framework added

### CODE REVIEW

**Comment by aaustin** [comment]
:+1:

**Comment by aaustin** [comment]
Can you resolve conflicts with master?

**Comment by antonargunov** [comment]
Only those with write access to this repository can merge pull requests.

**Comment by antonargunov** [comment]
Write me what files have conflict.

**Comment by aaustin** [comment]
Just gave you access

**Pull request merged**
