### PR TITLE
Fixing Issue#2 "Crash on link click"

### PR DESCRIPTION
**Pull request by antonargunov**
Changes:
*BranchUnityWrapper.java
*BranchAndroidWrapper.jar
*BranchUnityWrapper.unitypackage

### CODE REVIEW

**Comment by shortstuffsushi** [comment]
Your commit messages don't really explain what you're fixing here, can you explain how this fixes the crash? As far as I can tell, the activity is [only used for setting up the debug gesture](https://github.com/BranchMetrics/Branch-Android-SDK/blob/dc2a688f5d51e49978c3efe3e4089ddc2081c857/Branch-SDK/src/io/branch/referral/Branch.java#L861),  how did you determine this was the issue causing a crash?

**Comment by antonargunov** [comment]
Bug description:
Bug was in all methods initSession in Java class BranchUnityWrapper (file BranchUnityWrapper.java)

These methods call methods from Branch Android SDK, but don’t send current activity.

## For example:

Wrapper method calls this (see below) method from Android SDK

```
public class BranchUnityWrapper {
    …
    public static void initSession() {
        Activity unityActivity = UnityPlayer.currentActivity;
        Branch.getInstance(unityActivity.getApplicationContext(), _branchKey).initSessionWithData(unityActivity.getIntent().getData());
    }
    …
}
```

---

Android SDK method calls another method and send current activity as null

```
public class Branch {
    …
    public boolean initSessionWithData(Uri data) {
        return initSessionWithData(data, null);
    }

    public boolean initSessionWithData(Uri data, Activity activity) {
        boolean uriHandled = readAndStripParam(data, activity);
        initSession(null, activity);
        return uriHandled;
    }
    …
}
```

---

In the method named readAndStripParam the app send exception, because this method tries to use activity that equals null

```
activity.getIntent().setData(newData);
```

Bug fixing:

Now methods initSession in Java class BranchUnityWrapper (file BranchUnityWrapper.java) send current activity.

For example:

```
public class BranchUnityWrapper {
    …
    public static void initSession() {
        Activity unityActivity = UnityPlayer.currentActivity;
        Branch.getInstance(unityActivity.getApplicationContext(), _branchKey).initSessionWithData(unityActivity.getIntent().getData(), unityActivity);
    }
    …
}
```

**Comment by shortstuffsushi** [comment]
OK, after looking through the methods, I understand what you're saying. This is actually a bug that needs to be fixed in the Android SDK as well (though this fix will need to be used at least temporarily).

Can you please update the changelog with a more thorough description of what you fixed?

**Comment by shortstuffsushi** [comment]
Actually, since you're probably offline now, I'm going to go ahead and do this on our end + tag and upload a release. Thanks for this!

**Comment by antonargunov** [comment]
Sorry Graham, I fell asleep after non-stop fixing.
In BranchUnityWrapper in each of initSession methods I just add sending unityActivity to Android SDK.
You don't need fix Android SDK.

**Comment by shortstuffsushi** [comment]
Non-stop fixing hey? Sounds rough. Got some other projects going on too? Thanks for taking the time to contribute to ours as well :)

We do need to still fix the Android SDK separately, as we can't allow for NPEs to occur. This library was just one instance of how that could occur, and as a SDK that people drop into their projects, we want to be sure that we're never the ones causing those crashes with our lack of sanity checks.

**Pull request merged**
