### PR TITLE
SDK 1409 [Unity] Expose QR code creation methods

### PR DESCRIPTION
**Pull request by rob-gioia-branch**
## Reference
SDK 1409 [Unity] Expose QR code creation methods

## Summary
Enabled creation of QR codes using the Unity SDK. Android fully works, iOS may require a native SDK update to bridge the functionality. 

UnityQRDemo

## Motivation
To keep Unity up to date with our other SDKs

## Type Of Change

- [ ] New feature (non-breaking change which adds functionality)
- [ ] This change requires a documentation update

## Testing Instructions
- Use the _Generate QR Code_ button in the Branch Demo scene
- To modify the QR code being created go to BranchDemo.cs, line 143 and change the parameters used for the `OnBtn_GenerateQRCode()` function.

cc @BranchMetrics/saas-sdk-devs for visibility.

### CODE REVIEW

**Comment by nsingh-branch** [comment]
@rob-gioia-branch Just tested it on Android and it looks good. But i see the issue with iOS and the callBackWithData. What's required to be updated in the iOS SDK to fix this?

**Comment by rob-gioia-branch** [comment]
> @rob-gioia-branch Just tested it on Android and it looks good. But i see the issue with iOS and the callBackWithData. What's required to be updated in the iOS SDK to fix this?

Hi @nsingh-branch , thank you for reviewing! More details on the iOS issue here https://branch.slack.com/archives/CDFGXRM9S/p1692298562187739 but essentially:

- A function that takes in a parameter of NSData would need to be added to the BNCCallbacks class of the iOS SDK. Without that, none of the callbacks match the method signature needed for the QR code generation. (See the QR code function https://github.com/BranchMetrics/ios-branch-deep-linking-attribution/blob/master/BranchSDK/BranchQRCode.m#L58C1-L60C100 and the current BNC Callbacks we have access to https://github.com/BranchMetrics/ios-branch-deep-linking-attribution/blob/master/BranchSDK/BNCCallbacks.h)

**Comment by ahmednawar** [comment]
@nsingh-branch @rob-gioia-branch what's the next step here?

**Comment by nsingh-branch** [comment]
@ahmednawar There is a small change required on the native iOS side. It has been merged in and is currently just waiting on release.

**Comment by ahmednawar** [comment]
When is the release planned?

**Comment by nsingh-branch** [comment]
> When is the release planned?

I believe it will go out with the iOS 17 changes once those are ready.

**Comment by ahmednawar** [comment]
Did this go out?

**Comment by rob-gioia-branch** [comment]
> Did this go out?

Hey @ahmednawar ! Yes Nipun informed me that the new iOS SDK was released. I just need to make the change and test it in this Branch and then this will be good to go. Apologies, I've been swamped with lots of client questions but will look to get this done by early next week

**Comment by nsingh-branch** [comment]
@rob-gioia-branch Just wanted to check and see if this is ready to be merged and released or is more testing/review required?

**Comment by rob-gioia-branch** [comment]
Hi @nsingh-branch thanks for checking! There is currently one bug on iOS that I am still debugging and just started looking at again today. The request from Branch comes back with a 200 success code but the app freezes up with an invalid JSON write error. 

```
2024-01-02 16:30:41.713094-0500 BranchUnityTestBed[65009:393413] [branch.io] BranchQRCode.m(159) Debug: Network finish operation https://api3.branch.io/v1/qr-code 0.495s. Status 200.
2024-01-02 16:30:41.718777-0500 BranchUnityTestBed[65009:393413] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'Invalid type in JSON write (OS_dispatch_data)'
```

I'm going to take a deeper look tomorrow, may need a second set of eyes on it from you or @echo-branch if I still can't figure it out after that, because I don't want that one bug to keep holding up this task. Thanks!

**Review by nsingh-branch — APPROVED** [review]

**Pull request merged**
